<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-25LN50V" failures="9" tests="9" name="Default test" time="7.845" errors="0" timestamp="2024-08-17T13:57:00 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.091">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.011">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.01">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.013">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.008">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.01">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.009">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.009">
    <failure type="io.cucumber.java.PendingException" message="TODO: implement me">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at stepDefinition.DieticianPutStepDef.admin_is_logged_in_with_valid_credentials(DieticianPutStepDef.java:11)
at ✽.Admin is logged in with valid credentials(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/Dietician_Put.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.956">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;400&amp;gt; but was &amp;lt;401&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <401>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at stepDefinition.AdminLoginStepDef.user_send_post_http_request_with_endpoint(AdminLoginStepDef.java:67)
at ✽.User send POST HTTP request with endpoint(file:///C:/Users/chand/git/Team2_APIDietPhase2/src/test/resources/Features/User_Admin.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
