<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I6EP1Q3" failures="3" tests="4" name="testRunner.TestRunner" time="13.971" errors="0" timestamp="2024-08-21T17:46:33 IST" skipped="0">
  <testcase classname="testRunner.TestRunner" name="runScenario" time="1.147">
    <failure message="expected [403] but found [405]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [403] but found [405]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1449)
at stepDefinition.SetAdminToken_Steps_NegtaiveScenario.admin_recieves_forbidden(SetAdminToken_Steps_NegtaiveScenario.java:43)
at ✽.Admin recieves 403 forbidden(file:///C:/Users/mayan/git/Team2_APIRestAssured/Team2_APIDietPhase2/src/test/resources/Features/setAdminBearer.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="6.264"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="1.312">
    <failure message="expected [403] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [403] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1449)
at stepDefinition.SetAdminToken_Steps_NegtaiveScenario.admin_recieves_forbidden(SetAdminToken_Steps_NegtaiveScenario.java:43)
at ✽.Admin recieves 403 forbidden(file:///C:/Users/mayan/git/Team2_APIRestAssured/Team2_APIDietPhase2/src/test/resources/Features/setAdminBearer.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="5.248">
    <failure message="expected [403] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [403] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1449)
at stepDefinition.SetAdminToken_Steps_NegtaiveScenario.admin_recieves_forbidden(SetAdminToken_Steps_NegtaiveScenario.java:43)
at ✽.Admin recieves 403 forbidden(file:///C:/Users/mayan/git/Team2_APIRestAssured/Team2_APIDietPhase2/src/test/resources/Features/setAdminBearer.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.TestRunner -->
